[**@useactio/sdk**](../../README.md)

***

[@useactio/sdk](../../modules.md) / [error](../README.md) / TaskStillInProgressError

# Class: TaskStillInProgressError

Defined in: [src/error.ts:168](https://github.com/useactio/sdk/blob/aa0cbb7aefc891bd76a4e1447f8c84a24792d899/src/error.ts#L168)

Error thrown when trying to get a result from a task that is still in progress.

## Extends

- [`ActionCodesBaseError`](ActionCodesBaseError.md)

## Constructors

### Constructor

> **new TaskStillInProgressError**(`taskId`, `status`, `details?`): `TaskStillInProgressError`

Defined in: [src/error.ts:169](https://github.com/useactio/sdk/blob/aa0cbb7aefc891bd76a4e1447f8c84a24792d899/src/error.ts#L169)

#### Parameters

##### taskId

`string`

##### status

`string`

##### details?

`any`

#### Returns

`TaskStillInProgressError`

#### Overrides

[`ActionCodesBaseError`](ActionCodesBaseError.md).[`constructor`](ActionCodesBaseError.md#constructor)

## Properties

### code

> **code**: `string`

Defined in: [src/error.ts:21](https://github.com/useactio/sdk/blob/aa0cbb7aefc891bd76a4e1447f8c84a24792d899/src/error.ts#L21)

#### Inherited from

[`ActionCodesBaseError`](ActionCodesBaseError.md).[`code`](ActionCodesBaseError.md#code)

***

### details?

> `optional` **details**: `any`

Defined in: [src/error.ts:22](https://github.com/useactio/sdk/blob/aa0cbb7aefc891bd76a4e1447f8c84a24792d899/src/error.ts#L22)

#### Inherited from

[`ActionCodesBaseError`](ActionCodesBaseError.md).[`details`](ActionCodesBaseError.md#details)

***

### message

> **message**: `string`

Defined in: node\_modules/.pnpm/typescript@5.8.3/node\_modules/typescript/lib/lib.es5.d.ts:1077

#### Inherited from

[`ActionCodesBaseError`](ActionCodesBaseError.md).[`message`](ActionCodesBaseError.md#message)

***

### name

> **name**: `string`

Defined in: node\_modules/.pnpm/typescript@5.8.3/node\_modules/typescript/lib/lib.es5.d.ts:1076

#### Inherited from

[`ActionCodesBaseError`](ActionCodesBaseError.md).[`name`](ActionCodesBaseError.md#name)

***

### stack?

> `optional` **stack**: `string`

Defined in: node\_modules/.pnpm/typescript@5.8.3/node\_modules/typescript/lib/lib.es5.d.ts:1078

#### Inherited from

[`ActionCodesBaseError`](ActionCodesBaseError.md).[`stack`](ActionCodesBaseError.md#stack)

***

### stackTraceLimit

> `static` **stackTraceLimit**: `number`

Defined in: node\_modules/.pnpm/@types+node@22.15.34/node\_modules/@types/node/globals.d.ts:161

The `Error.stackTraceLimit` property specifies the number of stack frames
collected by a stack trace (whether generated by `new Error().stack` or
`Error.captureStackTrace(obj)`).

The default value is `10` but may be set to any valid JavaScript number. Changes
will affect any stack trace captured _after_ the value has been changed.

If set to a non-number value, or set to a negative number, stack traces will
not capture any frames.

#### Inherited from

[`ActionCodesBaseError`](ActionCodesBaseError.md).[`stackTraceLimit`](ActionCodesBaseError.md#stacktracelimit)

## Methods

### captureStackTrace()

> `static` **captureStackTrace**(`targetObject`, `constructorOpt?`): `void`

Defined in: node\_modules/.pnpm/@types+node@22.15.34/node\_modules/@types/node/globals.d.ts:145

Creates a `.stack` property on `targetObject`, which when accessed returns
a string representing the location in the code at which
`Error.captureStackTrace()` was called.

```js
const myObject = {};
Error.captureStackTrace(myObject);
myObject.stack;  // Similar to `new Error().stack`
```

The first line of the trace will be prefixed with
`${myObject.name}: ${myObject.message}`.

The optional `constructorOpt` argument accepts a function. If given, all frames
above `constructorOpt`, including `constructorOpt`, will be omitted from the
generated stack trace.

The `constructorOpt` argument is useful for hiding implementation
details of error generation from the user. For instance:

```js
function a() {
  b();
}

function b() {
  c();
}

function c() {
  // Create an error without stack trace to avoid calculating the stack trace twice.
  const { stackTraceLimit } = Error;
  Error.stackTraceLimit = 0;
  const error = new Error();
  Error.stackTraceLimit = stackTraceLimit;

  // Capture the stack trace above function b
  Error.captureStackTrace(error, b); // Neither function c, nor b is included in the stack trace
  throw error;
}

a();
```

#### Parameters

##### targetObject

`object`

##### constructorOpt?

`Function`

#### Returns

`void`

#### Inherited from

[`ActionCodesBaseError`](ActionCodesBaseError.md).[`captureStackTrace`](ActionCodesBaseError.md#capturestacktrace)

***

### prepareStackTrace()

> `static` **prepareStackTrace**(`err`, `stackTraces`): `any`

Defined in: node\_modules/.pnpm/@types+node@22.15.34/node\_modules/@types/node/globals.d.ts:149

#### Parameters

##### err

`Error`

##### stackTraces

`CallSite`[]

#### Returns

`any`

#### See

https://v8.dev/docs/stack-trace-api#customizing-stack-traces

#### Inherited from

[`ActionCodesBaseError`](ActionCodesBaseError.md).[`prepareStackTrace`](ActionCodesBaseError.md#preparestacktrace)
